// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqa7ZI_GM9KUFG15zz-LjMzY4gwt8fe7A',
    appId: '1:366356390775:web:85379ac76dbaa575eff772',
    messagingSenderId: '366356390775',
    projectId: 'mnotes-pro',
    authDomain: 'mnotes-pro.firebaseapp.com',
    storageBucket: 'mnotes-pro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWKeLRG4JqROHVj_qcQzGFViTgirHlxqM',
    appId: '1:366356390775:android:5a4be8a08127e7dbeff772',
    messagingSenderId: '366356390775',
    projectId: 'mnotes-pro',
    storageBucket: 'mnotes-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Mgp-KynSPZDiXTyrblhphcMbZLirkao',
    appId: '1:366356390775:ios:7b6c70612dfd3b90eff772',
    messagingSenderId: '366356390775',
    projectId: 'mnotes-pro',
    storageBucket: 'mnotes-pro.appspot.com',
    iosClientId: '366356390775-l1gkf05ngsa7jegt19ivjfsbdeapopl1.apps.googleusercontent.com',
    iosBundleId: 'se.shak.mnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Mgp-KynSPZDiXTyrblhphcMbZLirkao',
    appId: '1:366356390775:ios:5e99d7f6f850d73aeff772',
    messagingSenderId: '366356390775',
    projectId: 'mnotes-pro',
    storageBucket: 'mnotes-pro.appspot.com',
    iosClientId: '366356390775-3o0fr8uhupnq74873a4igiie7f2mo63d.apps.googleusercontent.com',
    iosBundleId: 'se.shak.mnotes.RunnerTests',
  );
}
